import { LotSettings, StaffUser, VehicleRecord, GateActivityItem } from '../types';

export const INITIAL_STAFF: StaffUser[] = [
  {
    id: 'staff-1',
    name: 'Ananya Sharma',
    email: 'operator@parkpay.in',
    role: 'staff',
    title: 'Lot operator · Gate 1',
    gate: 'Gate 1',
  },
  {
    id: 'staff-2',
    name: 'R. Kharkongor',
    email: 'admin@parkpay.in',
    role: 'admin',
    title: 'Lot Administrator',
    gate: 'HQ Control',
  },
];

export const INITIAL_SETTINGS: LotSettings = {
  lotName: 'Police Bazaar Parking · Gate 1',
  hourlyRate: 50,
  minimumCharge: 30,
  gracePeriodMinutes: 10,
  lastUpdatedBy: 'R. Kharkongor',
  lastUpdatedAt: '18 Sep 2026, 09:24',
  multipliers: {
    Car: 1.0,
    SUV: 1.2,
    Motorcycle: 0.5,
    Bus: 2.0,
    Truck: 2.0,
  },
};

// Generate realistic timestamps for today (23 Sep 2026)
const today = '2026-09-23';

export const INITIAL_VEHICLES: VehicleRecord[] = [
  // Active vehicles (as seen in OCR: currently parked 42)
  {
    id: 'v-act-1',
    plateNumber: 'ML05AB1234',
    vehicleType: 'Car',
    ownerPhone: '+91 98630 45192',
    entryTime: `${today}T11:54:00`,
    fee: 100,
    status: 'Parked',
    paymentStatus: 'Unpaid',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-act-2',
    plateNumber: 'AS01DN4421',
    vehicleType: 'SUV',
    ownerPhone: '+91 94350 18239',
    entryTime: `${today}T11:54:00`,
    fee: 150,
    status: 'Parked',
    paymentStatus: 'Unpaid',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-act-3',
    plateNumber: 'ML04C7788',
    vehicleType: 'Motorcycle',
    ownerPhone: '+91 98561 22345',
    entryTime: `${today}T11:54:00`,
    fee: 40,
    status: 'Parked',
    paymentStatus: 'Unpaid',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-act-4',
    plateNumber: 'NL01H9034',
    vehicleType: 'Car',
    ownerPhone: '+91 97740 55123',
    entryTime: `${today}T10:15:00`,
    fee: 150,
    status: 'Parked',
    paymentStatus: 'Unpaid',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-act-5',
    plateNumber: 'ML05E3321',
    vehicleType: 'Car',
    ownerPhone: '+91 98622 99014',
    entryTime: `${today}T12:10:00`,
    fee: 50,
    status: 'Parked',
    paymentStatus: 'Unpaid',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-act-6',
    plateNumber: 'AS01BC9981',
    vehicleType: 'SUV',
    ownerPhone: '+91 94361 88712',
    entryTime: `${today}T09:40:00`,
    fee: 200,
    status: 'Parked',
    paymentStatus: 'Unpaid',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-act-7',
    plateNumber: 'TR01D6623',
    vehicleType: 'Motorcycle',
    ownerPhone: '+91 98634 11098',
    entryTime: `${today}T12:45:00`,
    fee: 25,
    status: 'Parked',
    paymentStatus: 'Unpaid',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-act-8',
    plateNumber: 'ML05F8819',
    vehicleType: 'Car',
    ownerPhone: '+91 98630 88210',
    entryTime: `${today}T08:50:00`,
    fee: 250,
    status: 'Parked',
    paymentStatus: 'Unpaid',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-act-9',
    plateNumber: 'AS25C3344',
    vehicleType: 'Bus',
    ownerPhone: '+91 94351 90234',
    entryTime: `${today}T07:30:00`,
    fee: 600,
    status: 'Parked',
    paymentStatus: 'Unpaid',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-act-10',
    plateNumber: 'ML05G1122',
    vehicleType: 'Car',
    ownerPhone: '+91 98560 33412',
    entryTime: `${today}T13:05:00`,
    fee: 50,
    status: 'Parked',
    paymentStatus: 'Unpaid',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },

  // Additional 32 vehicles to reach exactly 42 currently parked vehicles
  ...Array.from({ length: 32 }).map((_, i) => {
    const types: ('Car' | 'SUV' | 'Motorcycle' | 'Bus' | 'Truck')[] = ['Car', 'Car', 'SUV', 'Motorcycle', 'Car', 'SUV', 'Truck'];
    const type = types[i % types.length];
    const states = ['ML05', 'ML04', 'AS01', 'AS25', 'TR01', 'NL01', 'MZ01'];
    const letters = ['AA', 'BC', 'CD', 'EF', 'GH', 'JK', 'LM', 'NP', 'RS'];
    const plate = `${states[i % states.length]}${letters[i % letters.length]}${1000 + i * 47}`;
    const hoursAgo = 1 + (i % 6);
    const minsAgo = (i * 13) % 60;
    const entryHour = Math.max(7, 13 - hoursAgo);
    const entryTimeString = `${today}T${String(entryHour).padStart(2, '0')}:${String(minsAgo).padStart(2, '0')}:00`;
    
    return {
      id: `v-act-gen-${i + 11}`,
      plateNumber: plate,
      vehicleType: type,
      ownerPhone: `+91 98630 ${String(10000 + i * 83).slice(0, 5)}`,
      entryTime: entryTimeString,
      fee: 50 + (i % 4) * 50,
      status: 'Parked' as const,
      paymentStatus: 'Unpaid' as const,
      loggedBy: 'Ananya Sharma',
      rateAppliedAtEntry: 50,
      graceMinutesAtEntry: 10,
      minimumChargeAtEntry: 30,
    };
  }),

  // Historical exited records matching OCR & Screen 4:
  {
    id: 'v-hist-1',
    plateNumber: 'ML05K2210',
    vehicleType: 'Car',
    ownerPhone: '+91 98630 11928',
    entryTime: `${today}T11:40:00`,
    exitTime: `${today}T13:30:00`,
    durationMinutes: 110,
    fee: 80,
    status: 'Exited',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    receiptNumber: 'PP-240923-087',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-hist-2',
    plateNumber: 'ML05AB1234',
    vehicleType: 'Car',
    ownerPhone: '+91 98630 45192',
    entryTime: `${today}T09:12:00`,
    exitTime: `${today}T11:00:00`,
    durationMinutes: 108,
    fee: 100,
    status: 'Exited',
    paymentStatus: 'Paid',
    paymentMethod: 'Cash',
    receiptNumber: 'PP-240923-074',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-hist-3',
    plateNumber: 'AS01DN4421',
    vehicleType: 'SUV',
    ownerPhone: '+91 94350 18239',
    entryTime: `${today}T08:24:00`,
    exitTime: `${today}T10:41:00`,
    durationMinutes: 137,
    fee: 140,
    status: 'Exited',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    receiptNumber: 'PP-240923-071',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-hist-4',
    plateNumber: 'ML04C7788',
    vehicleType: 'Motorcycle',
    ownerPhone: '+91 98561 22345',
    entryTime: `${today}T10:05:00`,
    exitTime: `${today}T10:41:00`,
    durationMinutes: 36,
    fee: 40,
    status: 'Exited',
    paymentStatus: 'Paid',
    paymentMethod: 'Cash',
    receiptNumber: 'PP-240923-069',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-hist-5',
    plateNumber: 'NL01H9034',
    vehicleType: 'Car',
    ownerPhone: '+91 97740 55123',
    entryTime: `${today}T07:52:00`,
    exitTime: `${today}T10:18:00`,
    durationMinutes: 146,
    fee: 140,
    status: 'Exited',
    paymentStatus: 'Paid',
    paymentMethod: 'Card',
    receiptNumber: 'PP-240923-062',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-hist-6',
    plateNumber: 'ML05D9988',
    vehicleType: 'SUV',
    ownerPhone: '+91 98630 77123',
    entryTime: `${today}T08:15:00`,
    exitTime: `${today}T09:45:00`,
    durationMinutes: 90,
    fee: 120,
    status: 'Exited',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    receiptNumber: 'PP-240923-055',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
  {
    id: 'v-hist-7',
    plateNumber: 'AS01AZ4512',
    vehicleType: 'Car',
    ownerPhone: '+91 94350 66211',
    entryTime: `${today}T06:50:00`,
    exitTime: `${today}T08:30:00`,
    durationMinutes: 100,
    fee: 100,
    status: 'Exited',
    paymentStatus: 'Unpaid',
    receiptNumber: 'PP-240923-048',
    loggedBy: 'Ananya Sharma',
    rateAppliedAtEntry: 50,
    graceMinutesAtEntry: 10,
    minimumChargeAtEntry: 30,
  },
];

export const INITIAL_GATE_ACTIVITY: GateActivityItem[] = [
  {
    id: 'act-1',
    timestamp: `${today}T13:39:00`,
    timeFormatted: '13:39',
    plateNumber: 'ML05AB1234',
    action: 'entered',
    vehicleType: 'Car',
  },
  {
    id: 'act-2',
    timestamp: `${today}T13:36:00`,
    timeFormatted: '13:36',
    plateNumber: 'AS01DN4421',
    action: 'exited',
    vehicleType: 'SUV',
    fee: 140,
  },
  {
    id: 'act-3',
    timestamp: `${today}T13:30:00`,
    timeFormatted: '13:30',
    plateNumber: 'ML05K2210',
    action: 'exited',
    vehicleType: 'Car',
    fee: 80,
  },
  {
    id: 'act-4',
    timestamp: `${today}T13:05:00`,
    timeFormatted: '13:05',
    plateNumber: 'ML05G1122',
    action: 'entered',
    vehicleType: 'Car',
  },
  {
    id: 'act-5',
    timestamp: `${today}T12:45:00`,
    timeFormatted: '12:45',
    plateNumber: 'TR01D6623',
    action: 'entered',
    vehicleType: 'Motorcycle',
  },
];

export const REVENUE_TREND_DAYS = [
  { day: 'WED', amount: 17200, exits: 76 },
  { day: 'THU', amount: 18900, exits: 84 },
  { day: 'FRI', amount: 24300, exits: 108 },
  { day: 'SAT', amount: 28500, exits: 132 },
  { day: 'SUN', amount: 26100, exits: 119 },
  { day: 'MON', amount: 16800, exits: 78 },
  { day: 'TUE', amount: 18450, exits: 87, isToday: true },
];

export const EXITS_BY_HOUR = [
  { hour: '08', exits: 6 },
  { hour: '10', exits: 14 },
  { hour: '12', exits: 22 },
  { hour: '14', exits: 18 },
  { hour: '16', exits: 12 },
  { hour: '18', exits: 9 },
  { hour: '20', exits: 6 },
];
